<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ListenableFutureAdapterTaskTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">threadly$All_in_threadly_test.exec</a> &gt; <a href="index.source.html" class="el_package">org.threadly.concurrent.future</a> &gt; <span class="el_source">ListenableFutureAdapterTaskTest.java</span></div><h1>ListenableFutureAdapterTaskTest.java</h1><pre class="source lang-java linenums">package org.threadly.concurrent.future;

import static org.junit.Assert.*;

import java.util.concurrent.ExecutionException;

import org.junit.Test;
import org.threadly.ThreadlyTester;
import org.threadly.util.ExceptionUtils;

@SuppressWarnings(&quot;javadoc&quot;)
<span class="fc" id="L12">public class ListenableFutureAdapterTaskTest extends ThreadlyTester {</span>
  @Test
  public void resultTest() throws InterruptedException, ExecutionException {
<span class="fc" id="L15">    Object result = new Object();</span>
<span class="fc" id="L16">    ListenableFutureAdapterTask&lt;Object&gt; adapter = </span>
<span class="fc" id="L17">        new ListenableFutureAdapterTask&lt;&gt;(FutureUtils.immediateResultFuture(result));</span>
    
<span class="fc" id="L19">    adapter.run();</span>

<span class="fc" id="L21">    assertTrue(adapter.isDone());</span>
<span class="pc bpc" id="L22" title="1 of 2 branches missed.">    assertTrue(result == adapter.get());</span>
<span class="fc" id="L23">  }</span>
  
  @Test
  public void cancelTest() {
<span class="fc" id="L27">    SettableListenableFuture&lt;Object&gt; slf = new SettableListenableFuture&lt;&gt;();</span>
<span class="fc" id="L28">    slf.cancel(false);</span>
<span class="fc" id="L29">    ListenableFutureAdapterTask&lt;Object&gt; adapter = new ListenableFutureAdapterTask&lt;&gt;(slf);</span>
    
<span class="fc" id="L31">    adapter.run();</span>
    
<span class="fc" id="L33">    assertTrue(adapter.isCancelled());</span>
<span class="fc" id="L34">  }</span>
  
  @Test
  public void exceptionFailureTest() throws InterruptedException {
<span class="fc" id="L38">    Exception failure = new Exception();</span>
<span class="fc" id="L39">    ListenableFutureAdapterTask&lt;Object&gt; adapter = </span>
<span class="fc" id="L40">        new ListenableFutureAdapterTask&lt;&gt;(FutureUtils.immediateFailureFuture(failure));</span>
    
<span class="fc" id="L42">    adapter.run();</span>

<span class="fc" id="L44">    assertTrue(adapter.isDone());</span>
    try {
<span class="nc" id="L46">      adapter.get();</span>
<span class="nc" id="L47">      fail(&quot;Exception shuld have thrown&quot;);</span>
<span class="fc" id="L48">    } catch (ExecutionException e) {</span>
<span class="pc bpc" id="L49" title="1 of 2 branches missed.">      assertTrue(failure == e.getCause());</span>
<span class="nc" id="L50">    }</span>
<span class="fc" id="L51">  }</span>
  
  @Test
  public void throwableFailureTest() throws InterruptedException {
<span class="fc" id="L55">    Throwable failure = new Throwable();</span>
<span class="fc" id="L56">    ListenableFutureAdapterTask&lt;Object&gt; adapter = </span>
<span class="fc" id="L57">        new ListenableFutureAdapterTask&lt;&gt;(FutureUtils.immediateFailureFuture(failure));</span>
    
<span class="fc" id="L59">    adapter.run();</span>

<span class="fc" id="L61">    assertTrue(adapter.isDone());</span>
    try {
<span class="nc" id="L63">      adapter.get();</span>
<span class="nc" id="L64">      fail(&quot;Exception shuld have thrown&quot;);</span>
<span class="fc" id="L65">    } catch (ExecutionException e) {</span>
<span class="pc bpc" id="L66" title="1 of 2 branches missed.">      assertTrue(failure == ExceptionUtils.getRootCause(e));</span>
<span class="nc" id="L67">    }</span>
<span class="fc" id="L68">  }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.1.201803210924</span></div></body></html>